// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

type MarkingTemplate struct {
	ID    string
	Bytes []byte
}

type PreprocessingTemplate struct {
	ID    string
	Bytes []byte
}

type Scan struct {
	ID                      string
	PreprocessingTemplateID string
	CreatedAtUnixMs         int64
}

type ScanPage struct {
	MatrixKey  string
	PictureKey string
	PageIndex  int64
	ScanID     string
}
