// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	CountScans(ctx context.Context) (int64, error)
	CreateMarkingTemplate(ctx context.Context, arg CreateMarkingTemplateParams) error
	CreatePreprocessingTemplate(ctx context.Context, arg CreatePreprocessingTemplateParams) error
	CreateScan(ctx context.Context, arg CreateScanParams) error
	CreateScanPage(ctx context.Context, arg CreateScanPageParams) error
	DeleteMarkingTemplate(ctx context.Context, id string) (int64, error)
	DeletePagesForScan(ctx context.Context, scanID string) (int64, error)
	DeletePreprocessingTemplate(ctx context.Context, id string) (int64, error)
	DeleteScan(ctx context.Context, id string) (int64, error)
	GetMarkingTemplate(ctx context.Context, id string) (MarkingTemplate, error)
	GetPagesForScan(ctx context.Context, scanID string) ([]ScanPage, error)
	GetPreprocessingTemplate(ctx context.Context, id string) (PreprocessingTemplate, error)
	GetScanPage(ctx context.Context, arg GetScanPageParams) (ScanPage, error)
	GetScansFromBefore(ctx context.Context, createdAtUnixMs int64) ([]Scan, error)
}

var _ Querier = (*Queries)(nil)
