// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"
)

const countAnchors = `-- name: CountAnchors :one
SELECT
    count(*)
FROM
    anchors
`

func (q *Queries) CountAnchors(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAnchors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScans = `-- name: CountScans :one
SELECT
    count(*)
FROM
    scans
`

func (q *Queries) CountScans(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnchor = `-- name: CreateAnchor :exec
INSERT INTO
    anchors (
        id,
        template_id,
        page_index,
        anchor_index
    )
VALUES
    (?, ?, ?, ?)
`

type CreateAnchorParams struct {
	ID          string
	TemplateID  string
	PageIndex   int64
	AnchorIndex int64
}

func (q *Queries) CreateAnchor(ctx context.Context, arg CreateAnchorParams) error {
	_, err := q.db.ExecContext(ctx, createAnchor,
		arg.ID,
		arg.TemplateID,
		arg.PageIndex,
		arg.AnchorIndex,
	)
	return err
}

const createMarkingTemplate = `-- name: CreateMarkingTemplate :exec
INSERT INTO
    marking_templates (id, json)
VALUES
    (?, ?)
`

type CreateMarkingTemplateParams struct {
	ID   string
	Json []byte
}

func (q *Queries) CreateMarkingTemplate(ctx context.Context, arg CreateMarkingTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createMarkingTemplate, arg.ID, arg.Json)
	return err
}

const createPreprocessingTemplate = `-- name: CreatePreprocessingTemplate :exec
INSERT INTO
    preprocessing_templates (id, json)
VALUES
    (?, ?)
`

type CreatePreprocessingTemplateParams struct {
	ID   string
	Json string
}

func (q *Queries) CreatePreprocessingTemplate(ctx context.Context, arg CreatePreprocessingTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createPreprocessingTemplate, arg.ID, arg.Json)
	return err
}

const createScan = `-- name: CreateScan :exec
INSERT INTO
    scans (id, preprocessing_template_id)
VALUES
    (?, ?)
`

type CreateScanParams struct {
	ID                      string
	PreprocessingTemplateID string
}

func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) error {
	_, err := q.db.ExecContext(ctx, createScan, arg.ID, arg.PreprocessingTemplateID)
	return err
}

const createScanPage = `-- name: CreateScanPage :exec
INSERT INTO
    scan_pages (id, picture_key, page_index, scan_id)
VALUES
    (?, ?, ?, ?)
`

type CreateScanPageParams struct {
	ID         string
	PictureKey string
	PageIndex  int64
	ScanID     string
}

func (q *Queries) CreateScanPage(ctx context.Context, arg CreateScanPageParams) error {
	_, err := q.db.ExecContext(ctx, createScanPage,
		arg.ID,
		arg.PictureKey,
		arg.PageIndex,
		arg.ScanID,
	)
	return err
}

const deleteAnchorsForTemplate = `-- name: DeleteAnchorsForTemplate :execrows
DELETE FROM
    anchors
WHERE
    template_id = ?
`

func (q *Queries) DeleteAnchorsForTemplate(ctx context.Context, templateID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAnchorsForTemplate, templateID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMarkingTemplate = `-- name: DeleteMarkingTemplate :execrows
DELETE FROM
    marking_templates
WHERE
    id = ?
`

func (q *Queries) DeleteMarkingTemplate(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMarkingTemplate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePagesForScan = `-- name: DeletePagesForScan :execrows
DELETE FROM
    scan_pages
WHERE
    scan_id = ?
`

func (q *Queries) DeletePagesForScan(ctx context.Context, scanID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePagesForScan, scanID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePreprocessingTemplate = `-- name: DeletePreprocessingTemplate :execrows
DELETE FROM
    preprocessing_templates
WHERE
    id = ?
`

func (q *Queries) DeletePreprocessingTemplate(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePreprocessingTemplate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteScan = `-- name: DeleteScan :execrows
DELETE FROM
    scans
WHERE
    id = ?
`

func (q *Queries) DeleteScan(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScan, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAnchorsForTemplate = `-- name: GetAnchorsForTemplate :many
SELECT
    id, template_id, page_index, anchor_index
FROM
    anchors
WHERE
    template_id = ?
ORDER BY
    page_index ASC,
    anchor_index ASC
`

func (q *Queries) GetAnchorsForTemplate(ctx context.Context, templateID string) ([]Anchor, error) {
	rows, err := q.db.QueryContext(ctx, getAnchorsForTemplate, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Anchor
	for rows.Next() {
		var i Anchor
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.PageIndex,
			&i.AnchorIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarkingTemplate = `-- name: GetMarkingTemplate :one
SELECT
    id, json
FROM
    marking_templates
WHERE
    id = ?
`

func (q *Queries) GetMarkingTemplate(ctx context.Context, id string) (MarkingTemplate, error) {
	row := q.db.QueryRowContext(ctx, getMarkingTemplate, id)
	var i MarkingTemplate
	err := row.Scan(&i.ID, &i.Json)
	return i, err
}

const getOneAnchorForTemplate = `-- name: GetOneAnchorForTemplate :one
SELECT
    id, template_id, page_index, anchor_index
FROM
    anchors
WHERE
    template_id = ?
    AND page_index = ?
    AND anchor_index = ?
`

type GetOneAnchorForTemplateParams struct {
	TemplateID  string
	PageIndex   int64
	AnchorIndex int64
}

func (q *Queries) GetOneAnchorForTemplate(ctx context.Context, arg GetOneAnchorForTemplateParams) (Anchor, error) {
	row := q.db.QueryRowContext(ctx, getOneAnchorForTemplate, arg.TemplateID, arg.PageIndex, arg.AnchorIndex)
	var i Anchor
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.PageIndex,
		&i.AnchorIndex,
	)
	return i, err
}

const getPagesForScan = `-- name: GetPagesForScan :many
SELECT 
    id, picture_key, page_index, scan_id
FROM
    scan_pages
WHERE
    scan_id = ?
ORDER BY
    page_index ASC
`

func (q *Queries) GetPagesForScan(ctx context.Context, scanID string) ([]ScanPage, error) {
	rows, err := q.db.QueryContext(ctx, getPagesForScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanPage
	for rows.Next() {
		var i ScanPage
		if err := rows.Scan(
			&i.ID,
			&i.PictureKey,
			&i.PageIndex,
			&i.ScanID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreprocessingTemplate = `-- name: GetPreprocessingTemplate :one
SELECT
    id, json
FROM
    preprocessing_templates
WHERE
    id = ?
`

func (q *Queries) GetPreprocessingTemplate(ctx context.Context, id string) (PreprocessingTemplate, error) {
	row := q.db.QueryRowContext(ctx, getPreprocessingTemplate, id)
	var i PreprocessingTemplate
	err := row.Scan(&i.ID, &i.Json)
	return i, err
}

const getScanPage = `-- name: GetScanPage :one
SELECT 
    id, picture_key, page_index, scan_id
FROM
    scan_pages
WHERE
    scan_id = ? AND
    page_index = ?
LIMIT 1
`

type GetScanPageParams struct {
	ScanID    string
	PageIndex int64
}

func (q *Queries) GetScanPage(ctx context.Context, arg GetScanPageParams) (ScanPage, error) {
	row := q.db.QueryRowContext(ctx, getScanPage, arg.ScanID, arg.PageIndex)
	var i ScanPage
	err := row.Scan(
		&i.ID,
		&i.PictureKey,
		&i.PageIndex,
		&i.ScanID,
	)
	return i, err
}

const getScansFromBefore = `-- name: GetScansFromBefore :many
SELECT
    id, preprocessing_template_id, created_at_unix_ms
FROM
    scans
WHERE
    created_at_unix_ms < ?
`

func (q *Queries) GetScansFromBefore(ctx context.Context, createdAtUnixMs int64) ([]Scan, error) {
	rows, err := q.db.QueryContext(ctx, getScansFromBefore, createdAtUnixMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(&i.ID, &i.PreprocessingTemplateID, &i.CreatedAtUnixMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
