// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"
)

const countScans = `-- name: CountScans :one
SELECT
    count(*)
FROM
    scans
`

func (q *Queries) CountScans(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMarkingTemplate = `-- name: CreateMarkingTemplate :exec
INSERT INTO
    marking_templates (id, bytes)
VALUES
    (?, ?)
`

type CreateMarkingTemplateParams struct {
	ID    string
	Bytes []byte
}

func (q *Queries) CreateMarkingTemplate(ctx context.Context, arg CreateMarkingTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createMarkingTemplate, arg.ID, arg.Bytes)
	return err
}

const createPreprocessingTemplate = `-- name: CreatePreprocessingTemplate :exec
INSERT INTO
    preprocessing_templates (id, bytes)
VALUES
    (?, ?)
`

type CreatePreprocessingTemplateParams struct {
	ID    string
	Bytes []byte
}

func (q *Queries) CreatePreprocessingTemplate(ctx context.Context, arg CreatePreprocessingTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createPreprocessingTemplate, arg.ID, arg.Bytes)
	return err
}

const createScan = `-- name: CreateScan :exec
INSERT INTO
    scans (id, preprocessing_template_id, created_at_unix_ms)
VALUES
    (?, ?, ?)
`

type CreateScanParams struct {
	ID                      string
	PreprocessingTemplateID string
	CreatedAtUnixMs         int64
}

func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) error {
	_, err := q.db.ExecContext(ctx, createScan, arg.ID, arg.PreprocessingTemplateID, arg.CreatedAtUnixMs)
	return err
}

const createScanPage = `-- name: CreateScanPage :exec
INSERT INTO
    scan_pages (matrix_key, picture_key, page_index, scan_id)
VALUES
    (?, ?, ?, ?)
`

type CreateScanPageParams struct {
	MatrixKey  string
	PictureKey string
	PageIndex  int64
	ScanID     string
}

func (q *Queries) CreateScanPage(ctx context.Context, arg CreateScanPageParams) error {
	_, err := q.db.ExecContext(ctx, createScanPage,
		arg.MatrixKey,
		arg.PictureKey,
		arg.PageIndex,
		arg.ScanID,
	)
	return err
}

const deleteMarkingTemplate = `-- name: DeleteMarkingTemplate :execrows
DELETE FROM
    marking_templates
WHERE
    id = ?
`

func (q *Queries) DeleteMarkingTemplate(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMarkingTemplate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePagesForScan = `-- name: DeletePagesForScan :execrows
DELETE FROM
    scan_pages
WHERE
    scan_id = ?
`

func (q *Queries) DeletePagesForScan(ctx context.Context, scanID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePagesForScan, scanID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePreprocessingTemplate = `-- name: DeletePreprocessingTemplate :execrows
DELETE FROM
    preprocessing_templates
WHERE
    id = ?
`

func (q *Queries) DeletePreprocessingTemplate(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePreprocessingTemplate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteScan = `-- name: DeleteScan :execrows
DELETE FROM
    scans
WHERE
    id = ?
`

func (q *Queries) DeleteScan(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScan, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMarkingTemplate = `-- name: GetMarkingTemplate :one
SELECT
    id, bytes
FROM
    marking_templates
WHERE
    id = ?
`

func (q *Queries) GetMarkingTemplate(ctx context.Context, id string) (MarkingTemplate, error) {
	row := q.db.QueryRowContext(ctx, getMarkingTemplate, id)
	var i MarkingTemplate
	err := row.Scan(&i.ID, &i.Bytes)
	return i, err
}

const getPagesForScan = `-- name: GetPagesForScan :many
SELECT 
    matrix_key, picture_key, page_index, scan_id
FROM
    scan_pages
WHERE
    scan_id = ?
ORDER BY
    page_index ASC
`

func (q *Queries) GetPagesForScan(ctx context.Context, scanID string) ([]ScanPage, error) {
	rows, err := q.db.QueryContext(ctx, getPagesForScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanPage
	for rows.Next() {
		var i ScanPage
		if err := rows.Scan(
			&i.MatrixKey,
			&i.PictureKey,
			&i.PageIndex,
			&i.ScanID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreprocessingTemplate = `-- name: GetPreprocessingTemplate :one
SELECT
    id, bytes
FROM
    preprocessing_templates
WHERE
    id = ?
`

func (q *Queries) GetPreprocessingTemplate(ctx context.Context, id string) (PreprocessingTemplate, error) {
	row := q.db.QueryRowContext(ctx, getPreprocessingTemplate, id)
	var i PreprocessingTemplate
	err := row.Scan(&i.ID, &i.Bytes)
	return i, err
}

const getScanPage = `-- name: GetScanPage :one
SELECT 
    matrix_key, picture_key, page_index, scan_id
FROM
    scan_pages
WHERE
    scan_id = ? AND
    page_index = ?
LIMIT 1
`

type GetScanPageParams struct {
	ScanID    string
	PageIndex int64
}

func (q *Queries) GetScanPage(ctx context.Context, arg GetScanPageParams) (ScanPage, error) {
	row := q.db.QueryRowContext(ctx, getScanPage, arg.ScanID, arg.PageIndex)
	var i ScanPage
	err := row.Scan(
		&i.MatrixKey,
		&i.PictureKey,
		&i.PageIndex,
		&i.ScanID,
	)
	return i, err
}

const getScansFromBefore = `-- name: GetScansFromBefore :many
SELECT
    id, preprocessing_template_id, created_at_unix_ms
FROM
    scans
WHERE
    created_at_unix_ms < ?
`

func (q *Queries) GetScansFromBefore(ctx context.Context, createdAtUnixMs int64) ([]Scan, error) {
	rows, err := q.db.QueryContext(ctx, getScansFromBefore, createdAtUnixMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(&i.ID, &i.PreprocessingTemplateID, &i.CreatedAtUnixMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
