// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type PdfRenderCost struct {
	EntryID            int64
	SampledAt          int64
	PdfRenderBaseline  int64
	PdfRenderIncrement int64
}
