// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreatePdfRenderCosts(ctx context.Context, arg CreatePdfRenderCostsParams) error
	GetPdfRenderCosts(ctx context.Context) (PdfRenderCost, error)
}

var _ Querier = (*Queries)(nil)
