// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateCpuLimit(ctx context.Context, maxThreads int64) error
	CreateMemoryLimit(ctx context.Context, maxMemory int64) error
	CreatePdfRenderCosts(ctx context.Context, arg CreatePdfRenderCostsParams) error
	DeleteCpuLimit(ctx context.Context, entryID int64) error
	DeleteMemoryLimit(ctx context.Context, entryID int64) error
	GetCpuLimit(ctx context.Context) (CpuLimit, error)
	GetMemoryLimit(ctx context.Context) (MemoryLimit, error)
	GetPdfRenderCosts(ctx context.Context) (PdfRenderCost, error)
}

var _ Querier = (*Queries)(nil)
