// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
)

const createCpuLimit = `-- name: CreateCpuLimit :exec
INSERT INTO
    cpu_limits (max_threads)
VALUES
    (?)
`

func (q *Queries) CreateCpuLimit(ctx context.Context, maxThreads int64) error {
	_, err := q.db.ExecContext(ctx, createCpuLimit, maxThreads)
	return err
}

const createMemoryLimit = `-- name: CreateMemoryLimit :exec
INSERT INTO
    memory_limits (max_memory)
VALUES
    (?)
`

func (q *Queries) CreateMemoryLimit(ctx context.Context, maxMemory int64) error {
	_, err := q.db.ExecContext(ctx, createMemoryLimit, maxMemory)
	return err
}

const createPdfRenderCosts = `-- name: CreatePdfRenderCosts :exec
INSERT INTO
    pdf_render_costs (pdf_render_baseline, pdf_render_increment)
VALUES
    (?, ?)
`

type CreatePdfRenderCostsParams struct {
	PdfRenderBaseline  int64
	PdfRenderIncrement int64
}

func (q *Queries) CreatePdfRenderCosts(ctx context.Context, arg CreatePdfRenderCostsParams) error {
	_, err := q.db.ExecContext(ctx, createPdfRenderCosts, arg.PdfRenderBaseline, arg.PdfRenderIncrement)
	return err
}

const deleteCpuLimit = `-- name: DeleteCpuLimit :exec
DELETE FROM
    cpu_limits
WHERE
    ? = entry_id
`

func (q *Queries) DeleteCpuLimit(ctx context.Context, entryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCpuLimit, entryID)
	return err
}

const deleteMemoryLimit = `-- name: DeleteMemoryLimit :exec
DELETE FROM
    memory_limits
WHERE
    ? = entry_id
`

func (q *Queries) DeleteMemoryLimit(ctx context.Context, entryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMemoryLimit, entryID)
	return err
}

const getCpuLimit = `-- name: GetCpuLimit :one
SELECT 
    entry_id, created_at, max_threads
FROM
    cpu_limits
ORDER BY
    created_at DESC
LIMIT 1
`

func (q *Queries) GetCpuLimit(ctx context.Context) (CpuLimit, error) {
	row := q.db.QueryRowContext(ctx, getCpuLimit)
	var i CpuLimit
	err := row.Scan(&i.EntryID, &i.CreatedAt, &i.MaxThreads)
	return i, err
}

const getMemoryLimit = `-- name: GetMemoryLimit :one
SELECT 
    entry_id, created_at, max_memory
FROM
    memory_limits
ORDER BY
    created_at DESC
LIMIT 1
`

func (q *Queries) GetMemoryLimit(ctx context.Context) (MemoryLimit, error) {
	row := q.db.QueryRowContext(ctx, getMemoryLimit)
	var i MemoryLimit
	err := row.Scan(&i.EntryID, &i.CreatedAt, &i.MaxMemory)
	return i, err
}

const getPdfRenderCosts = `-- name: GetPdfRenderCosts :one
SELECT 
    entry_id, sampled_at, pdf_render_baseline, pdf_render_increment
FROM
    pdf_render_costs
ORDER BY
    sampled_at DESC
LIMIT 1
`

func (q *Queries) GetPdfRenderCosts(ctx context.Context) (PdfRenderCost, error) {
	row := q.db.QueryRowContext(ctx, getPdfRenderCosts)
	var i PdfRenderCost
	err := row.Scan(
		&i.EntryID,
		&i.SampledAt,
		&i.PdfRenderBaseline,
		&i.PdfRenderIncrement,
	)
	return i, err
}
