// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
)

const createPdfRenderCosts = `-- name: CreatePdfRenderCosts :exec
INSERT INTO
    pdf_render_costs (pdf_render_baseline, pdf_render_increment)
VALUES
    (?, ?)
`

type CreatePdfRenderCostsParams struct {
	PdfRenderBaseline  int64
	PdfRenderIncrement int64
}

func (q *Queries) CreatePdfRenderCosts(ctx context.Context, arg CreatePdfRenderCostsParams) error {
	_, err := q.db.ExecContext(ctx, createPdfRenderCosts, arg.PdfRenderBaseline, arg.PdfRenderIncrement)
	return err
}

const getPdfRenderCosts = `-- name: GetPdfRenderCosts :one
SELECT 
    entry_id, sampled_at, pdf_render_baseline, pdf_render_increment
FROM
    pdf_render_costs
ORDER BY
    entry_id DESC
LIMIT 1
`

func (q *Queries) GetPdfRenderCosts(ctx context.Context) (PdfRenderCost, error) {
	row := q.db.QueryRowContext(ctx, getPdfRenderCosts)
	var i PdfRenderCost
	err := row.Scan(
		&i.EntryID,
		&i.SampledAt,
		&i.PdfRenderBaseline,
		&i.PdfRenderIncrement,
	)
	return i, err
}
