// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Course struct {
	ID       uuid.UUID
	Name     string
	Semester string
}

type Enrolment struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	CourseID uuid.UUID
	Role     string
}

type Exam struct {
	ID           uuid.UUID
	CourseID     uuid.UUID
	CreatedBy    uuid.UUID
	Name         string
	VersionLabel sql.NullString
	ExamDate     sql.NullTime
	CreatedAt    sql.NullTime
}

type ExamGrade struct {
	ID              uuid.UUID
	OmrMarkingID    uuid.UUID
	ExamTemplateID  uuid.UUID
	QuestionResults json.RawMessage
	TotalScore      sql.NullString
	MaxScore        sql.NullString
	TemplateVersion sql.NullInt32
	GradedAt        sql.NullTime
}

type ExamTemplate struct {
	ID             uuid.UUID
	ExamID         uuid.UUID
	QuestionConfig json.RawMessage
	AnswerKey      json.RawMessage
	ScoringRules   pqtype.NullRawMessage
	TotalQuestions int32
	Version        sql.NullInt32
}

type OmrDetectedMark struct {
	ID              uuid.UUID
	MarkingID       uuid.UUID
	QuestionNumber  int32
	DetectedValue   sql.NullString
	ConfidenceScore sql.NullFloat64
	NeedsReview     sql.NullBool
	X               sql.NullInt32
	Y               sql.NullInt32
	Width           sql.NullInt32
	Height          sql.NullInt32
}

type OmrMarking struct {
	ID            uuid.UUID
	ScanID        uuid.UUID
	OmrTemplateID uuid.UUID
	Status        sql.NullString
	ErrorMessage  sql.NullString
	CreatedAt     sql.NullTime
	StartedAt     sql.NullTime
	FinishedAt    sql.NullTime
}

type OmrTemplate struct {
	ID        uuid.UUID
	Name      string
	PageCount int32
	Version   sql.NullInt32
	CreatedAt sql.NullTime
}

type ReviewRequest struct {
	ID                 uuid.UUID
	ExamGradeID        uuid.UUID
	StudentID          uuid.UUID
	QuestionNumber     sql.NullString
	StudentComment     sql.NullString
	Status             sql.NullString
	InstructorResponse sql.NullString
	CreatedAt          sql.NullTime
	ResolvedAt         sql.NullTime
}

type Scan struct {
	ID             uuid.UUID
	ExamID         uuid.UUID
	UploaderUserID uuid.UUID
	Path           string
	PageCount      sql.NullInt32
}

type User struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
	Role         string
	CreatedAt    sql.NullTime
}
