// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sql

import (
	"context"
)

const getScan = `-- name: GetScan :one
SELECT id, exam_id, uploader_user_id, path, page_count FROM scans LIMIT 1
`

func (q *Queries) GetScan(ctx context.Context) (Scan, error) {
	row := q.db.QueryRowContext(ctx, getScan)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.UploaderUserID,
		&i.Path,
		&i.PageCount,
	)
	return i, err
}
