// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Anchor struct {
	ID          string
	TemplateID  string
	PageIndex   int64
	AnchorIndex int64
}

type MarkingTemplate struct {
	ID   string
	Json []byte
}

type PreprocessingTemplate struct {
	ID   string
	Json string
}

type Scan struct {
	ID                      string
	PreprocessingTemplateID string
	CreatedAt               int64
}

type ScanPage struct {
	ID         string
	PictureKey string
	PageIndex  int64
	ScanID     string
}
