// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountAnchors(ctx context.Context) (int64, error)
	CountScans(ctx context.Context) (int64, error)
	CreateAnchor(ctx context.Context, arg CreateAnchorParams) error
	CreateMarkingTemplate(ctx context.Context, arg CreateMarkingTemplateParams) error
	CreatePreprocessingTemplate(ctx context.Context, arg CreatePreprocessingTemplateParams) error
	CreateScan(ctx context.Context, arg CreateScanParams) error
	CreateScanPage(ctx context.Context, arg CreateScanPageParams) error
	GetAnchorsForTemplate(ctx context.Context, templateID string) ([]Anchor, error)
	GetMarkingTemplate(ctx context.Context, id string) (MarkingTemplate, error)
	GetOneAnchorForTemplate(ctx context.Context, arg GetOneAnchorForTemplateParams) (Anchor, error)
	GetPreprocessingTemplate(ctx context.Context, id string) (PreprocessingTemplate, error)
	GetScanPage(ctx context.Context, arg GetScanPageParams) (ScanPage, error)
	GetScanPages(ctx context.Context, scanID string) ([]ScanPage, error)
}

var _ Querier = (*Queries)(nil)
