// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateMarkingTemplate(ctx context.Context, arg CreateMarkingTemplateParams) error
	CreatePreprocessingTemplate(ctx context.Context, arg CreatePreprocessingTemplateParams) error
}

var _ Querier = (*Queries)(nil)
