// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
)

const createMarkingTemplate = `-- name: CreateMarkingTemplate :exec
INSERT INTO marking_templates (
    id,
    json
)
VALUES (?, ?)
`

type CreateMarkingTemplateParams struct {
	ID   string
	Json string
}

func (q *Queries) CreateMarkingTemplate(ctx context.Context, arg CreateMarkingTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createMarkingTemplate, arg.ID, arg.Json)
	return err
}

const createPreprocessingTemplate = `-- name: CreatePreprocessingTemplate :exec
INSERT INTO preprocessing_templates (
    id,
    json
)
VALUES (?, ?)
`

type CreatePreprocessingTemplateParams struct {
	ID   string
	Json string
}

func (q *Queries) CreatePreprocessingTemplate(ctx context.Context, arg CreatePreprocessingTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createPreprocessingTemplate, arg.ID, arg.Json)
	return err
}
