services:
  garage:
    image: dxflrs/garage:v2.3.0
    restart: unless-stopped
    env_file: ./config/garage.env
    entrypoint: /garage
    command: server --single-node --default-bucket
    ports:
      - 3900:3900
      - 3901:3901
      - 3902:3902
      - 3903:3903
    volumes:
      - ./config/garage.toml:/etc/garage.toml
      - /var/lib/garage/meta:/var/lib/garage/meta
      - /var/lib/garage/data:/var/lib/garage/data