package sys

import (
	"sync"
	"testing"
)

//
// Helpers
//

func assertSlicesEqual[T comparable](t *testing.T, got, want []T) {
	t.Helper()

	if len(got) != len(want) {
		t.Fatalf("length mismatch: got %d, want %d\n got: %v\nwant: %v",
			len(got), len(want), got, want)
	}

	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("item %d mismatch: got %v, want %v\n got: %v\nwant: %v",
				i, got[i], want[i], got, want)
		}
	}
}

//
// Tests
//
// (Some of these tests are generated by an LLM)
//

func TestRingBufferEmpty(t *testing.T) {
	r := NewRingBuffer[int](5)

	if got := r.Len(); got != 0 {
		t.Fatalf("expected length 0, got %d", got)
	}

	if got := r.Get(5); len(got) != 0 {
		t.Fatalf("expected empty slice, got %v", got)
	}
}

func TestRingBufferAddAndGet(t *testing.T) {
	r := NewRingBuffer[int](5)

	for i := 1; i <= 3; i++ {
		r.Add(i)
	}

	if got := r.Len(); got != 3 {
		t.Fatalf("expected length 3, got %d", got)
	}

	want := []int{1, 2, 3}
	got := r.Get(3)

	assertSlicesEqual(t, got, want)
}

func TestRingBufferCapacityLimit(t *testing.T) {
	r := NewRingBuffer[int](3)

	for i := 1; i <= 5; i++ {
		r.Add(i)
	}

	if got := r.Len(); got != 3 {
		t.Fatalf("expected length 3, got %d", got)
	}

	// Oldest entries should have been discarded.
	want := []int{3, 4, 5}
	got := r.Get(3)

	assertSlicesEqual(t, got, want)
}

func TestRingBufferGetLessThanLength(t *testing.T) {
	r := NewRingBuffer[int](5)

	for i := 1; i <= 5; i++ {
		r.Add(i)
	}

	want := []int{3, 4, 5}
	got := r.Get(3)

	assertSlicesEqual(t, got, want)
}

func TestRingBufferGetMoreThanLength(t *testing.T) {
	r := NewRingBuffer[int](5)

	for i := 1; i <= 3; i++ {
		r.Add(i)
	}

	want := []int{1, 2, 3}
	got := r.Get(10)

	assertSlicesEqual(t, got, want)
}

func TestRingBufferGetZero(t *testing.T) {
	r := NewRingBuffer[int](5)

	for i := 1; i <= 3; i++ {
		r.Add(i)
	}

	got := r.Get(0)

	if len(got) != 0 {
		t.Fatalf("expected empty slice, got %v", got)
	}
}

func TestRingBufferGetNegative(t *testing.T) {
	r := NewRingBuffer[int](5)

	for i := 1; i <= 3; i++ {
		r.Add(i)
	}

	got := r.Get(-1)

	if len(got) != 0 {
		t.Fatalf("expected empty slice, got %v", got)
	}
}

func TestRingBufferGenericType(t *testing.T) {
	type item struct {
		Value string
	}

	r := NewRingBuffer[item](2)

	r.Add(item{Value: "a"})
	r.Add(item{Value: "b"})

	want := []item{
		{Value: "a"},
		{Value: "b"},
	}

	assertSlicesEqual(t, r.Get(2), want)
}

func TestRingBufferReturnedSliceIsIndependent(t *testing.T) {
	r := NewRingBuffer[int](3)

	r.Add(1)
	r.Add(2)
	r.Add(3)

	got := r.Get(3)
	got[0] = 100

	want := []int{1, 2, 3}
	assertSlicesEqual(t, r.Get(3), want)
}

func TestRingBufferConcurrentAccess(t *testing.T) {
	r := NewRingBuffer[int](100)

	var wg sync.WaitGroup

	const writers = 10
	const readers = 10
	const writesPerWriter = 1000

	for i := range writers {
		wg.Add(1)

		go func(offset int) {
			defer wg.Done()

			for j := range writesPerWriter {
				r.Add(offset*writesPerWriter + j)
			}
		}(i)
	}

	for range readers {
		wg.Go(func() {
			for range writesPerWriter {
				_ = r.Get(10)
				_ = r.Len()
			}
		})
	}

	wg.Wait()

	if got := r.Len(); got != 100 {
		t.Fatalf("expected final length 100, got %d", got)
	}
}
