openapi: 3.0.3

info:
  title: OMR Service
  version: "0.0.1"
  description: |
    A service to perform Optical Mark Recognition (OMR) on scans of bubblesheets.

servers:
  - url: http://localhost:3000/

tags:
  - name: Health
    description: Service health and availability
  - name: Scan
    description: Image scans of exams
  - name: Preprocessing
    description: Data for preprocessing scans
  - name: Template
    description: Templates for processing scans

components:
  schemas:

    PreprocessTemplate:
      type: object
      required:
        - width
        - height
        - anchors
        - config
      properties:
        width:
          type: integer
          minimum: 1
        height:
          type: integer
          minimum: 1

        anchors:
          type: array
          minItems: 3
          maxItems: 3
          items:
            $ref: '#/components/schemas/Anchor'

        config:
          $ref: '#/components/schemas/PreprocessConfig'

    Anchor:
      type: object
      required:
        - center
        - roi
      properties:
        center:
          $ref: '#/components/schemas/Point'

        roi:
          $ref: '#/components/schemas/Rectangle'

    Point:
      type: object
      required:
        - x
        - y
      properties:
        x:
          type: integer
        y:
          type: integer

    Rectangle:
      type: object
      required:
        - min
        - max
      properties:
        min:
          $ref: '#/components/schemas/Point'
        max:
          $ref: '#/components/schemas/Point'

    PreprocessConfig:
      type: object
      required:
        - blurSize
        - morphCloseSize
        - minAnchorConfidence
      properties:
        blurSize:
          type: integer
          minimum: 1

        morphCloseSize:
          type: integer
          minimum: 1

        minAnchorConfidence:
          type: number
          format: float
          minimum: 0
          maximum: 1

paths:
  /health:
    get:
      tags:
        - Health
      summary: Ping the Service
      description: |
        Simple health-check endpoint. Confirms that the service is running and has a database connection.
      responses:
        "200":
          description: The service is functional.
        "500":
          description: The service failed to connect to the database. Check the server logs.
  /upload:
    post:
      tags:
        - Scan
      summary: Upload a Scan
      description: |
        Simple upload endpoint. Accepts a `multipart/form-data` body that has an `image` field set to an `image/tiff` file. The uploaded image will be stored with a unique key which is specified in the response body.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - image
              properties:
                image:
                  type: string
                  format: binary
                  description: TIFF image file
            encoding:
              image:
                contentType: image/tiff
      responses:
        "200":
          description: The image was successfully uploaded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - imageId
                properties:
                  imageId:
                    type: string
                    description: The new UUID for the image.
        "500":
          description: There was an error storing the image.
          content: 
            text/plain:
              schema:
                type: string
        "400":
          description: The request body was malformed. See the response body for details.
          content:
            text/plain:
              schema:
                type: string
    get:
      tags:
        - Scan
      summary: Retrieve a Scan
      description: |
        Retrieves an uploaded scan by its unique key.
      parameters:
        - name: imageId
          in: query
          required: true
          description: UUID of the uploaded scan.
          schema:
            type: string
      responses:
        "200":
          description: The image was successfully retrieved.
          content:
            image/tiff:
              schema:
                type: string
                format: binary
        "500":
          description: There was an error connecting to the file storage.
          content:
            text/plain:
              schema:
                type: string
        "404":
          description: No image with the specified key was found.
          content:
            text/plain:
              schema:
                type: string
    delete:
      tags:
        - Scan
      summary: Delete a Scan
      description: |
        Deletes an uploaded scan by its unique key. If the image isn't found, the request is still considered successful.
      parameters:
        - name: imageId
          in: query
          required: true
          description: Unique key of the uploaded scan.
          schema:
            type: string
      responses:
        "200":
          description: The image is deleted.
        "500":
          description: There was an error connecting to the file storage.
          content:
            text/plain:
              schema:
                type: string

  /template/preprocess:
    post:
      summary: Upload a Preprocessing Template
      tags:
        - Preprocessing
        - Template
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - anchor0
                - anchor1
                - anchor2
                - template
              properties:
                anchor0:
                  type: string
                  format: binary
                  description: First anchor image

                anchor1:
                  type: string
                  format: binary
                  description: Second anchor image

                anchor2:
                  type: string
                  format: binary
                  description: Third anchor image

                template:
                  $ref: '#/components/schemas/PreprocessTemplate'

            encoding:
              template:
                contentType: application/json

      responses:
        "501":
          description: Not implemented

        "400":
          description: Invalid request
          content:
            text/plain:
              schema:
                type: string
              examples:
                invalidMultipart:
                  value: invalid multipart form
                missingAnchor:
                  value: anchor0 is required
                invalidImage:
                  value: failure decoding anchor0; ensure its type is image/*
                missingTemplate:
                  value: template field required
                invalidTemplate:
                  value: error parsing template JSON data, ensure it matches the specified format
      